### ISSUE TITLE
Search filter UX

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#120]
We got some early user feedback that it is not clear what to do after changing search filters. Presently, once the user has added agency/OIG filters, they have to click the search button or press enter to apply them. This isn't intuitive, partly because the search button doesn't read strongly as something you can interact with, and partly because nothing on a keyboard is intuitive.

We could solve this in a couple ways:

- Add a more obvious search/apply/submit button nearer to the search filters (maybe even two apply buttons, one after the agency filter and one after the date filter)

- Use JS to automatically submit the form when the user leaves the agency filter box, picks a date, or clicks on an unreleased/FOIA'd/featured bubble

Personally, I'm leaning toward the "additional buttons" solution, but I'd like to get a little input first. Thoughts?

/cc @heyitsolivia would greatly appreciate your expertise on this

**Comment by heyitsolivia** [comment]
@divergentdave I'd opt for both, actually. I think intuitively someone would expect any kind of search filters to be applied immediately, so we should automatically submit with js whenever the user changes the parameters of the search. But providing a button is also necessary as a non-js solution and also so that a user can manually submit if needed.
