### ISSUE TITLE
Move the site to new server(s)

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#66]
The site is running in shared space on an EC2 instance I personally operate, cotenant with konklone.com and some other little things. It's time to move this into its own space, to more easily share access and to avoid other issues.

The site has 3 main components:

* The Node app.
* The IG scrapers (Python, unitedstates/inspectors-general), and the ES data loading scripts (Ruby, in this repo).
* The Elasticsearch database itself.

I'm up for changing anything and everything about hosting, within reasonable cost, to make it easier and more stable for everyone.

**Comment by divergentdave** [comment]
Key ElasticSearch statistics from our current cluster:
- One node, one shard
- 47652 documents
- ES reports that its store is 2.7GB
- JVM heap is 133.6MB right now, and had a maximum size of 1015MB

**Comment by divergentdave** [comment]
@spulec have been talking about how best to set up the infrastructure, particularly on AWS. None of this is to rule out DigitalOcean droplets, or other server hosting providers, but here's what we think so far.

The three biggest improvements we could make on AWS are doing scraping/ingestion on spot instances, autoscaling how many webserver intsances are running, and maybe using AWS's "Amazon Elasticsearch Service" in lieu of running the service on a multipurpose instance.

Spot instances would be a great fit for the scraping and ingestion scripts, since these are the most resource intensive parts of the site, and yet they are mostly idempotent. If the spot instance gets killed due to rising prices, then that particular run doesn't make it all the way through scraping and ingestion, but the next run can pick up where it left off without issue. For this to work out, we would put the `data` directory on EBS storage, and have the scrape/ingest instance attach to that volume. Furthermore, we could terminate the scrape/ingest instance once one run has completed, and avoid paying for it to idle until the next run. For reference, the current server runs its cron job every three hours. Since we're using EBS, the scrape/ingest instance will be tied to one availability zone, but generally speaking I don't think we need to worry about uptime enough to try spanning AZs.

The web server could be placed in an instance on its own, in an "autoscaling group" in case we need to spin up more than one. Having the web server separated from the scrapers and database would simplify this greatly, in case the site ever gets too successful. Beyond scaling, if we set up the autoscaling group properly, then the same configuration and bootstrapping will come in handy if there is ever a hardware problem with the server, or we need to tear it down and rebuild for some reason. Once the boostrapping script is written, AWS can get the server back online without any intervention from us. We should also modify the Fabfile to deploy to all of the web server instances, in case that is ever more than one.

There isn't much magic to Amazon Elasticsearch Service, as it just runs on top of EC2 instances, but it would be nice to have management of that service taken care of. Given our dataset, we can stick with a one-node cluster. Nodes can store their data either on ephemeral "instance storage" or EBS volumes, so we will need another EBS volume to back the Elasticsearch node. (as mentioned above, this is only 2.7GB so far) Apparently there is a "free" Elasticsearch instance available for use, although it has only 1GB of memory. Given the above high watermark of 1015MB for the JVM heap, this could be too little, but we could always try it out.

If we wanted to trade the ability to scale for simplicity, we could also run our own Elasticsearch service and the Node.js server on one instance, and do all the scraping on spot instances to still get the cost savings there. @konklone, based on usage patterns, can you speak to how much of the cost is driven by scraping vs. hosting the website? Thoughts appreciated from all!

**Comment by konklone** [comment]
@divergentdave very little cost is driven by scraping -- the network activity is minimal. The pricing is all for the server itself, which is very low (since I share it with a couple other sites). It's an EC2 m3.medium with an EBS or two attached. The IG reports have their own EBS.

I'm a little skeptical of wiring the system up with Spot Instances -- it seems like overkill, and potentially more costly through having one-instance-per-scrape than by having an instance stay up and run all the scrapers without interruption.

I like splitting the app from the scrapers from the ES DB, and would love configuration mgmt to quickly bootstrap a server up out of nowhere. However, I am also skeptical of the need for much auto-scaling. I am suspicious the site is ever going to get *so* successful it needs auto-scaling. Even when isitchristmas.com has 4000 people on-site at once, a single medium instance with nginx proxying to two parallel Node app processes on the same box has always had no problem at all. The hefty files, the PDFs themselves, we'll mostly be linking out to the IGs and having them (appropriately) absorb the bandwidth. (There are going to be cases where we don't do this in the future, but even then I am not overly concerned, and we're likely to store them in S3 rather than serve them off-disk.)

I'm interested in the AWS Elasticsearch service as opposed to running our own node -- though it increases cost, it seems like a smarter idea for a bunch of reasons. I think we can get away with a `t2.small` there.

What about we do something like the following:

* `t2.small` EC2 instance that runs nginx and the Node web app, which connects to the AWS ES instance for reading. Is stateless except for the HTTPS certificate. Can use a bootstrap script or configuration management to make it easy to respin the server and get a new Let's Encrypt certificate as needed.
* `t2.small` EC2 instance that runs the scrapers, and then connects to the AWS ES instance for writing to do the data loading after scrapers are done. Is stateless except for the EBS. Can use a bootstrap script or configuration management to make it easy to respin the server and attach the EBS as needed.
* `t2.small` AWS ES instance that the other instances use. I'm not totally familiar with how AWS manages this behind the scenes.

Thoughts? And should I create some IAM users?

**Comment by divergentdave** [comment]
Sounds good to me!

Regarding the Let's Encrypt cert and key, we should hang onto those somewhere persistent and encrypted rather than get a new one, since they're still rate limiting issuance at this phase. (if that hasn't changed recently)

**Comment by divergentdave** [comment]
Alright, one of the next steps in bringing this up is the EBS volume for the data directory. @konklone, can you create a snapshot of the EBS volume behind `data-200` on the current server? I think if you make that snapshot public, then we can create a new EBS instance based on that snapshot inside the new IAM group, and then throw away the snapshot. Then we can attach the new EBS instance to the launch configuration and go from there.

**Comment by divergentdave** [comment]
(P.S. please let me know if I'm getting my AWS concepts wrong)

**Comment by konklone** [comment]
@divergentdave I think your concepts are right. I've initiated a snapshot of the data-200 EBS, and made the snapshot's permissions public. Its snapshot ID is `snap-0be44c0d`. It's still `pending` as of this comment. Once that's done, I'll initiate the creation of an EBS from it in the new account.

**Comment by divergentdave** [comment]
FYI stood this up as vol-029063be101599653 in the new account.

**Comment by divergentdave** [comment]
Hmm, I'm thinking running the scraper on an instance in an "auto-scaling group" may have been the wrong abstraction. I don't see a way to have the EBS volume automatically attach to an instance in the auto-scaling group, which makes sense, because that would fall apart with two instances in the group.

Is there another way of starting instances besides auto-scaling groups and manually starting an instance from scratch? I like the idea of doing all the configuration from the "user-data" script, can we do the same without the auto-scaling group layer? Is the AWS-y answer to just make your own AMI and run that in an instance?

**Comment by divergentdave** [comment]
Declaring victory on this one
