### ISSUE TITLE
Tiny blog

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#70]
Thought: a small blog, on oversight.io itself, where we can put the launch post, and potentially permalink versions of anything we send out on Tinyletter. It'd be nice to help the site accrue PageRank and overall awareness.

This could easily get more annoying and complicated than it's worth, and I'm even up for just hardcoding a single page to get it started and not building a whole blogging engine.

**Comment by audiodude** [comment]
I'm interested in taking this issue.

**Comment by konklone** [comment]
Go for it!

**Comment by audiodude** [comment]
Okay, so I've created a very basic system using [Wintersmith](https://github.com/jnordberg/wintersmith) which was the most embeddable static content generator I could find.

So basically it works like this:

1. Globally install wintersmith using npm
1. Install the node module for wintersmith-ejs
1. Create a post in ./blog/, the name of the file on disk can be separated from the URL filename using the `filename` param in the frontmatter
1. Use `$ wintersmith build --config=blog-config.js`
1. The files end up in /public/blog, where they are already served statically by express

Also, because of using wintersmith-ejs, the blog-post.ejs template uses header.html and footer.html from the main site.

Additional work could be done to create a blog index with pagination and such things. But for your bare bones, let's throw up some static content that we author using Markdown, this does it.

**Comment by audiodude** [comment]
This assumes that blog posts will be committed and part of the repo, of course, which seems like a good assumption and good practice.

**Comment by divergentdave** [comment]
:+1: on keeping blog posts in the repo

**Comment by divergentdave** [comment]
[Blogging works!](https://oversight.garden/blog/blogging-works/)

**Comment by konklone** [comment]
It sure does!
